export const dataList = [
  {
    id: 1,
    title: '優格水果杯',
    foodWeight: 200,
    calories: 110,
    protein: 4,
    fat:1,
    category: 'dish',
    cuisine: 'breakfast',
    rating: 2,
    coverSrc: '/ImageMenu/fatLoseMeal/藍莓優格.jpg',
  },
  {
    id: 2,
    title: '燕麥片',
    foodWeight: 40,
    protein: 5,
    category: 'dish',
    cuisine: 'breakfast',
    rating: 4,
    calories: 150,
    fat:2.5,
    coverSrc: '/ImageMenu/fatLoseMeal/燕麥片.jpg',
  },
  {
    id: 3,
    title: '烤全麥吐司',
    foodWeight: 40,
    protein: 5,
    category: 'dish',
    cuisine: 'breakfast',
    rating: 4,
    calories: 120,
    fat:2.5,
    coverSrc: '/ImageMenu/fatLoseMeal/全麥土司.jpg',
  },
];