export const categoryList = [
 
    {
        id: 1,
        value: 'place',
        label: '一般',
      },
      {
        id: 2,
        value: 'dish',
        label: '素食',
      },
  ];
  
  export const ratingList = [
    {
      id: 1,
      value: '1',
      label: '1👍',
    },
    {
      id: 2,
      value: '2',
      label: '2👍',
    },
    {
      id: 3,
      value: '3',
      label: '3👍',
    },
    {
      id: 4,
      value: '4',
      label: '4👍',
    },
    {
      id: 5,
      value: '5',
      label: '5👍',
    },
  ];
  
  export const dataList = [
    {
      id: 1,
      title: '優格水果杯',
      foodWeight: 200,
      calories: 110,
      protein: 4,
      fat:1,
      category: 'dish',
      cuisine: 'breakfast',
      rating: 2,
      coverSrc: '/ImageMenu/fatLoseMeal/藍莓優格.jpg',
    },
    {
      id: 2,
      title: '燕麥片',
      foodWeight: 40,
      protein: 5,
      category: 'dish',
      cuisine: 'breakfast',
      rating: 1,
      calories: 150,
      fat:2.5,
      coverSrc: '/ImageMenu/fatLoseMeal/燕麥片.jpg',
    },
    {
      id: 3,
      title: '烤全麥吐司',
      foodWeight: 40,
      protein: 5,
      category: 'dish',
      cuisine: 'breakfast',
      rating: 1,
      calories: 120,
      fat:2.5,
      coverSrc: '/ImageMenu/fatLoseMeal/全麥土司.jpg',
    },
    {
      id: 4,
      title: '水煮蛋',
      foodWeight: 50,
      protein: 5,
      category: 'place',
      cuisine: 'breakfast',
      rating: 1,
      calories: 70,
      fat:5,
      coverSrc: '/ImageMenu/fatLoseMeal/水煮蛋.jpg',
    },
    {
      id: 5,
      title: '烤蕃薯',
      foodWeight: 100,
      calories: 90,
      protein: 1,
      fat:0,
      category: 'dish',
      cuisine: 'breakfast',
      rating: 2,
      coverSrc: '/ImageMenu/fatLoseMeal/烤蕃薯.jpg',
    },
    {
      id: 6,
      title: '荷包蛋',
      foodWeight: 50,
      calories: 140,
      protein: 9,
      fat:11,
      category: 'place',
      cuisine: 'breakfast',
      rating: 2,
      coverSrc: '/ImageMenu/fatLoseMeal/荷包蛋.jpg',
    },
    {
      id: 7,
      title: '蔬菜煎蛋',
      foodWeight: 100,
      calories: 120,
      protein: 7,
      fat:8.5,
      category: 'place',
      cuisine: 'breakfast',
      rating: 2,
      coverSrc: '/ImageMenu/fatLoseMeal/蔬菜煎蛋.jpg',
    },
    {
      id: 8,
      title: '燕麥蘋果粥',
      foodWeight: 100,
      calories: 120,
      protein: 3,
      fat:2.5,
      category: 'dish',
      cuisine: 'breakfast',
      rating: 2,
      coverSrc: '/ImageMenu/fatLoseMeal/蘋果燕麥.jpg',
    },
    {
      id: 9,
      title: '燕麥蛋白燉蛋',
      foodWeight: 100,
      calories: 130,
      protein: 11,
      fat:5,
      category: 'place',
      cuisine: 'breakfast',
      rating: 3,
      coverSrc: '/ImageMenu/fatLoseMeal/燕麥燉蛋.jpg',
    },
    {
      id: 10,
      title: '草莓酸奶',
      foodWeight: 200,
      calories: 120,
      protein: 4,
      fat:4,
      category: 'dish',
      cuisine: 'breakfast',
      rating: 4,
      coverSrc: '/ImageMenu/fatLoseMeal/草莓優格.jpg',
    },
    {
      id: 11,
      title: '炒蛋番茄',
      foodWeight: 100,
      calories: 70,
      protein: 5,
      fat:5,
      category: 'place',
      cuisine: 'breakfast',
      rating: 3,
      coverSrc: '/ImageMenu/fatLoseMeal/番茄炒蛋.jpg',
    },
    {
      id: 12,
      title: '烤香蕉',
      foodWeight: 100,
      calories: 90,
      protein: 1,
      fat:0.5,
      category: 'dish',
      cuisine: 'breakfast',
      rating: 2,
      coverSrc: '/ImageMenu/fatLoseMeal/烤香蕉.jpg',
    },
     {
      id: 14,
      title: '烤雞胸肉',
      foodWeight: 100,
      calories: 165,
      protein: 31,
      fat:3.6,
      category: 'place',
      cuisine: 'lunch',
      rating: 1,
      coverSrc: '/ImageMenu/fatLoseMeal/雞胸肉.jpg',
    },
    {
      id: 15,
      title: '紅豆糙米飯',
      foodWeight: 100,
      calories: 140,
      protein: 4,
      fat:1.5,
      category: 'dish',
      cuisine: 'lunch',
      rating: 4,
      coverSrc: '/ImageMenu/fatLoseMeal/紅豆飯.jpg',
    },
    {
      id: 16,
      title: '清炒青菜',
      foodWeight: 200,
      calories: 50,
      protein: 2,
      fat:0.5,
      category: 'dish',
      cuisine: 'dinner',
      rating: 3,
      coverSrc: '/ImageMenu/fatLoseMeal/炒青菜.jpg',
    },
    {
      id: 17,
      title: '清蒸鯛魚',
      foodWeight: 100,
      calories: 80,
      protein: 15,
      fat:1.5,
      category: 'place',
      cuisine: 'lunch',
      rating: 5,
      coverSrc: '/ImageMenu/fatLoseMeal/蒸鯛魚.jpg',
    },
    {
      id: 18,
      title: '酸辣湯',
      foodWeight: 300,
      calories: 120,
      protein: 7,
      fat:1.5,
      category: 'place',
      cuisine: 'lunch',
      rating: 5,
      coverSrc: '/ImageMenu/fatLoseMeal/酸辣湯.jpg',
    },
    {
      id: 19,
      title: '清蒸鮭魚',
      foodWeight: 100,
      calories: 120,
      protein: 20,
      fat:5,
      category: 'place',
      cuisine: 'lunch',
      rating: 5,
      coverSrc: '/ImageMenu/fatLoseMeal/蒸鮭魚.jpg',
    },
    {
      id: 20,
      title: '韓式拌飯',
      foodWeight: 100,
      calories: 150,
      protein: 5,
      fat:1.5,
      category: 'place',
      cuisine: 'lunch',
      rating: 4,
      coverSrc: '/ImageMenu/fatLoseMeal/韓式拌飯.jpg',
    },
    {
      id: 21,
      title: '烤豬肉排',
      foodWeight: 100,
      calories: 180,
      protein: 23,
      fat:9,
      category: 'place',
      cuisine: 'lunch',
      rating: 4,
      coverSrc: '/ImageMenu/fatLoseMeal/豬肉排.jpg',
    },
    {
      id: 22,
      title: '紅燒豆腐',
      foodWeight: 100,
      calories: 90,
      protein: 7,
      fat:3.5,
      category: 'dish',
      cuisine: 'lunch',
      rating: 5,
      coverSrc: '/ImageMenu/fatLoseMeal/紅燒豆腐1.jpg',

    },
    {
      id: 23,
      title: '紅燒排骨',
      foodWeight: 100,
      calories: 240,
      protein: 19,
      fat:15,
      category: 'place',
      cuisine: 'lunch',
      rating: 5,
      coverSrc: '/ImageMenu/fatLoseMeal/紅燒排骨.jpg',
    },
    {
      id: 24,
      title: '紅燒雞翅',
      foodWeight: 100,
      calories: 220,
      protein: 18,
      fat:12,
      category: 'place',
      cuisine: 'lunch',
      rating: 4,
      coverSrc: '/ImageMenu/fatLoseMeal/紅燒雞翅.jpg',
    },
    {
      id: 25,
      title: '煎三文魚',
      foodWeight: 100,
      calories: 220,
      protein: 25,
      fat:13,
      category: 'place',
      cuisine: 'lunch',
      rating: 5,
      coverSrc: '/ImageMenu/fatLoseMeal/煎三文魚.jpg',
    },
    {
      id: 26,
      title: '煮雞胸肉',
      foodWeight: 100,
      calories: 120,
      protein: 24,
      fat:2,
      category: 'place',
      cuisine: 'lunch',
      rating: 3,
      coverSrc: '/ImageMenu/fatLoseMeal/雞胸肉.jpg',
    },
    {
      id: 27,
      title: '清蒸海鮮',
      foodWeight: 100,
      calories: 100,
      protein: 20,
      fat:1,
      category: 'place',
      cuisine: 'lunch',
      rating: 4,
      coverSrc: '/ImageMenu/fatLoseMeal/蒸海鮮.jpg',
    },
    {
      id: 28,
      title: '清蒸龍利魚',
      foodWeight: 100,
      calories: 90,
      protein: 20,
      fat:1.5,
      category: 'place',
      cuisine: 'lunch',
      rating: 5,
      coverSrc: '/ImageMenu/fatLoseMeal/龍利魚.jpg',
    },
    {
      id: 29,
      title: '紅燒鰻魚',
      foodWeight: 100,
      calories: 250,
      protein: 20,
      fat:14,
      category: 'place',
      cuisine: 'lunch',
      rating: 3,
      coverSrc: '/ImageMenu/Bmr01.jpg',
    },
    {
      id: 30,
      title: '燉蔬菜湯',
      foodWeight: 300,
      calories: 100,
      protein: 4,
      fat:1.5,
      category: 'dish',
      cuisine: 'lunch',
      rating: 1,
      coverSrc: '/ImageMenu/fatLoseMeal/蔬菜湯.jpg',
    },
    {
      id: 31,
      title: '印度咖哩雞肉',
      foodWeight: 100,
      calories: 165,
      protein: 21,
      fat:5.5,
      category: 'place',
      cuisine: 'dinner',
      rating: 4,
      coverSrc: '/ImageMenu/fatLoseMeal/咖哩雞.jpg',
    },
   
    {
      id: 33,
      title: '紅燒牛肉麵',
      foodWeight: 100,
      calories: 200,
      protein: 18,
      fat:3.5,
      category: 'place',
      cuisine: 'dinner',
      rating: 5,
      coverSrc: '/ImageMenu/fatLoseMeal/牛肉麵.jpg',
    },
    {
      id: 34,
      title: '紅燒茄子',
      foodWeight: 100,
      calories: 85,
      protein: 3,
      fat:2.5,
      category: 'dish',
      cuisine: 'dinner',
      rating: 1,
      coverSrc: '/ImageMenu/fatLoseMeal/炒茄子.jpg',
    },
    {
      id: 35,
      title: '清炒豆芽菜',
      foodWeight: 200,
      calories: 40,
      protein: 2,
      fat:0.5,
      category: 'dish',
      cuisine: 'dinner',
      rating: 1,
      coverSrc: '/ImageMenu/fatLoseMeal/豆芽菜.jpg',
    },
    {
      id: 36,
      title: '炒蛋',
      foodWeight: 100,
      calories: 80,
      protein: 6,
      fat:5.5,
      category: 'place',
      cuisine: 'dinner',
      rating: 3,
      coverSrc: '/ImageMenu/fatLoseMeal/炒蛋.jpg',
    },
    {
      id: 37,
      title: '烤三文魚',
      foodWeight: 100,
      calories: 200,
      protein: 25,
      fat:10,
      category: 'place',
      cuisine: 'dinner',
      rating: 3,
      coverSrc: '/ImageMenu/fatLoseMeal/煎三文魚.jpg',
    },
    {
      id: 38,
      title: '麻婆豆腐',
      foodWeight: 100,
      calories: 200,
      protein: 14,
      fat:10,
      category: 'dish',
      cuisine: 'dinner',
      rating: 3,
      coverSrc: '/ImageMenu/fatLoseMeal/麻婆豆腐.jpg',
    },
    {
      id: 39,
      title: '炒高麗菜',
      foodWeight: 200,
      calories: 40,
      protein: 3,
      fat:0.5,
      category: 'dish',
      cuisine: 'dinner',
      rating: 1,
      coverSrc: '/ImageMenu/fatLoseMeal/炒高麗菜.jpg',
    },
    {
      id: 40,
      title: '炒素麵',
      foodWeight:100,
      calories: 150,
      protein: 4,
      fat:1.5,
      category: 'dish',
      cuisine: 'dinner',
      rating: 2,
      coverSrc: '/ImageMenu/fatLoseMeal/素麵.jpg',
    },
    {
      id: 41,
      title: '爆炒蘑菇',
      foodWeight:100,
      calories: 70,
      protein: 3,
      fat:4,
      category: 'dish',
      cuisine: 'dinner',
      rating: 2,
      coverSrc: '/ImageMenu/fatLoseMeal/炒蘑菇.jpg',
    },
    {
      id: 42,
      title: '紅燒鱸魚',
      foodWeight:100,
      calories: 220,
      protein: 20,
      fat:12,
      category: 'place',
      cuisine: 'dinner',
      rating: 4,
      coverSrc: '/ImageMenu/Bmr01.jpg',
    },
    {
      id: 43,
      title: '涼拌海帶絲',
      foodWeight:100,
      calories: 60,
      protein: 1,
      fat:0.5,
      category: 'dish',
      cuisine: 'dinner',
      rating: 5,
      coverSrc: '/ImageMenu/fatLoseMeal/炒海帶.jpg',
    },
     
  ];